
### Get Users

GET http://127.0.0.1:8000/api/users
Content-Type: application/json





### Make a User
POST http://127.0.0.1:8000/api/users/signup
Content-Type: application/json

{
    "firstName": "Brian",
    "lastName": "Codington",
    "email": "bcod14@gmail.com",
    "username": "bcod",
    "password": "123456",
    "confirmPassword": "123456",
    "isLandLord": false

}

### Delete a User

DELETE http://127.0.0.1:8000/api/users/617b76b7e9fd71c02a6436cb
Content-Type: application/json



### Get Reviews

GET http://127.0.0.1:8000/api/reviews
Content-Type: application/json


### Make Review

POST http://127.0.0.1:8000/api/reviews
Content-Type: application/json

{
    "reviewText": "This is a test review, round 6",
    "priceRating": 1,
    "houseRating": 1,
    "nicenessRating": 1,
    "depositReurnRating": 1,
    "creatorId": "1"
}

### Update a Review
PATCH http://127.0.0.1:8000/api/reviews/618a0b7fb69359fadd14c05c
Content-Type: application/json

{
    "reviewText": "I completely changed this reviews text XD"
}


### Delete a Review
DELETE http://127.0.0.1:8000/api/reviews/618a0b7fb69359fadd14c05c
Content-Type: application/json

### Get all Landlords

GET http://127.0.0.1:8000/api/landlords
Content-Type: application/json


### Make a Landlord

POST http://127.0.0.1:8000/api/landlords
Content-Type: application/json

{
    "name": "Kid Cod"
}

### Update a Landlord 

PATCH http://127.0.0.1:8000/api/landlords/6189dad711b474c2c3ea0533
Content-Type: application/json

{
    "name": "Kid Cod"
}

### Delete a Landlord

DELETE http://127.0.0.1:8000/api/landlords/6189cce5c564b7d74709fa8e
Content-Type: application/json

### get specific landlord

GET http://127.0.0.1:8000/api/landlords/61b55075a42a8d5dcad27c4b
Content-Type: application/json

### add a review to a landlord profile
PATCH http://127.0.0.1:8000/api/landlords/reviews/61b55075a42a8d5dcad27c4b
Content-Type: application/json

{
    "reviewId": "61b551e392a07d9c8750f44c"
}